### ISSUE TITLE
Japanese is hard to transliterate

### ISSUE THREAD

**Issue by cireficc** [norman/unidecoder#13]
This example, which is part of the test suite, is grossly wrong:

`"私はガラスを食べられます。それは私を傷つけません。" => "Si hagarasuwoShi beraremasu. sorehaSi woShang tukemasen. "`

The correct transliteration is:

`"私はガラスを食べられます。それは私を傷つけません。" => "watashi wa garasu o taberaremasu. sore wa watashi o kizutukemasen. "`

Looks like the library is recognizing Chinese characters and doing the 1:1 substitution, when it should be recognizing the language as Japanese and transliterating differently. But I don't think that trying to include Japanese transliteration is a good idea. It's an open NLP problem and libraries like [Mecab](https://github.com/taku910/mecab) try to accomplish the task.

One idea would be to bundle that library as a dependency and use it for Japanese specifically. In any case, having blatantly wrong transliterations is kind of pointless, right?

**Comment by cireficc** [comment]
Scratch that - just read the README (go figure). You already mention that Japanese transliteration is useless; closing!

**Comment by mahemoff** [comment]
The solution to Japanese seems to be [Natto](https://github.com/buruzaemon/natto), though it's a bit tricky to setup as it relies on the underlying MeCab C library.

Absent that, I would guess for many use cases, it's better to avoid this library for Japanese strings. It might even be useful if the library has an option to return null or whatever if it detects Japanese (or analogous situations with other languages/alphabet mismatches).

**Comment by cireficc** [comment]
@mahemoff Yes, I think returning null for unsupported languages would be a good idea. Japanese especially, and maybe other languages without 1:1 mappings like Russian and various varieties of Arabic.

Transliteration is useful, but unfortunately is not straightforward in many languages...
